package com.nhl.model.playoffbracket;

public enum SeedingLabel {

	FIRSTROUNDDIV1WINNER,
	FIRSTROUNDDIV1RUNNERUP,
	FIRSTROUNDDIV2WINNER,
	FIRSTROUNDDIV2RUNNERUP,
	DIV1FINALS,
	DIV2FINALS,
	CONFERENCEFINALS,
	FINALS
	
}
